version: 0.2

phases:
  install:
    commands:
      - apt update && apt install -y mingw-w64 curl
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
  build:
    commands:
      - cargo run --release