[package]
edition.workspace = true
license.workspace = true
name = "rsrss"
publish.workspace = true
version = "1.0.0"

[workspace]
members = ["adapter", "crawler", "kernel", "registry", "shared"]

[[bin]]
name = "rsrss"
path = "src/bin/app.rs"

[workspace.package]
edition = "2021"
license = "MIT"
publish = false

[workspace.dependencies]
adapter = { path = "./adapter" }
anyhow = "1.0.98"
async-trait = "0.1.88"
chrono = { version = "0.4.41", features = ["serde"] }
chrono-tz = "0.10.3"
const_format = { version = "0.2.34", features = ["derive"] }
crawler = { path = "./crawler" }
derive-new = "0.7.0"
dotenvy = "0.15.7"
feed-parser = "1.0.11"
fxhash = "0.2.1"
indicatif = "0.17.11"
kernel = { path = "./kernel" }
keyword-tools = { git = "https://github.com/akitenkrad/keywords", branch = "main" }
openai-tools = "0.1.3"
regex = "1.11.1"
registry = { path = "./registry" }
request = { version = "0.12.15", features = ["cookies"], package = "reqwest" }
scraper = "0.23.1"
serde = "1.0.219"
serde_json = "1.0.140"
shared = { path = "./shared" }
sqlx = { version = "0.8.5", features = [
    "runtime-tokio",
    "uuid",
    "chrono",
    "macros",
    "postgres",
    "migrate",
] }
tokio = { version = "1.45.0", features = ["full"] }
tokio-test = "0.4.4"
thiserror = "2.0.12"
tracing = { version = "0.1.41", features = ["log"] }
urlencoding = "2.1.3"
uuid = { version = "1.16.0", features = ["v4", "serde"] }

[dependencies]
