[package]
edition = "2021"
name = "rsrss"
version = "0.1.0"

[dependencies]
keywords = { git = "https://github.com/akitenkrad/keywords", branch="main" }
async-trait = "0.1.83"
chrono = ">=0.4"
chrono-tz = ">=0.10.0"
dotenv = "0.15.0"
feed-parser = "1.0.1"
futures = "0.3.31"
log = "0.4.22"
quick-xml = { version = "0.36.2", features = ["serialize"] }
regex = "1.11.0"
reqwest = ">=0.12"
scraper = ">=0.20"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = { version = ">=1.4", features = ["full"] }
tokio-test = "0.4.4"
urlencoding = ">=2.0"
indicatif = "0.17.8"
