services:
  rsrss:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8080:8080
    env_file:
      - .env
    tty: true
    user: root
    # entrypoint: "/app/target/release/rsrss start-dashboard"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rsrss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres:
    external: true