services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8080:8080
    env_file:
      - .env
    user: root
    entrypoint: "/app/target/release/server start-dashboard"
    depends_on:
      - postgres
  front:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
    env_file:
      - .env
    user: root
    entrypoint: ["nginx", "-g", "daemon off;"]
    depends_on:
      - server
  postgres:
    image: postgres:latest
    user: root
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - data:/data:cached
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rsrss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # PGDATA: /var/lib/postgresql/data
      PGDATA: /data/postgres/data

volumes:
  postgres:
    external: true
  data:
    external: true