FROM node:latest AS builder
WORKDIR /app

COPY react-front /app/
RUN npm install && \
    npm install react-scripts -g && \
    npm run build

FROM nginx:alpine AS runtime
COPY --from=builder /app/build /usr/share/nginx/html
COPY react-front/nginx.conf /etc/nginx/conf.d/default.conf
