[config]
default_to_workspace = false

[env]
env_file = ".env"

[tasks.migrate]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }
script = '''
#!/bin/bash
until sqlx migrate run --source adapter/migrations; do
  sleep 1
done
'''

[tasks.compose-up-db]
command = "docker"
args = ["compose", "up", "-d", "postgres"]

[tasks.before-build]
run_task = [{ name = ["compose-up-db", "migrate"] }]

[tasks.compose-build]
script = '''
#!/bin/bash
docker compose build --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1
'''

[tasks.compose-build-no-cache]
command = "docker"
args = ["compose", "build", "--pull", "--no-cache", "--progress=plain"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "${@}"]
dependencies = ["before-build"]

[tasks.run-debug]
command = "cargo"
args = ["run", "${@}"]
dependencies = ["before-build"]

[tasks.run-in-docker]
args = ["compose", "run", "--rm", "rsrss", "${@}"]
command = "docker"
dependencies = ["before-build"]
env_files = [".env"]

[tasks.logs]
command = "docker"
args = ["compose", "logs", "${@}"]
dependencies = ["before-build"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]
dependencies = ["before-build"]

[tasks.reformat]
script = '''
#!/bin/bash
cargo fmt -- --emit files
'''

[tasks.nextest]
dependencies = ["before-build"]
script = '''
#!/bin/bash
docker run --rm rsrss cargo nextest run --workspace --status-level all --test-threads=1 "${@}"
'''

command = "cargo"
args = [
  "nextest",
  "run",
  "--workspace",
  "--status-level",
  "all",
  "--test-threads=1",
]
install_crate = "cargo-nextest"

[tasks.migrate-revert]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }
script = '''
#!/bin/bash
migration=$(find adapter/migrations -type f -name "*down.sql" | sort -r)
for m in ${migration[@]}; do
  echo "Reverting migrations for $m"
  until sqlx migrate revert --source adapter/migrations; do
    sleep 1
  done
done
'''

[tasks.migration-logs]
command = "docker"
args = [
  "run",
  "-it",
  "--rm",
  "--network",
  "host",
  "-v",
  "${PWD}:/work",
  "postgres:latest",
  "psql",
  "${DATABASE_URL}",
  "-c",
  "SELECT * FROM \"_sqlx_migrations\" ORDER BY \"version\" DESC",
]

[tasks.sqlx]
command = "sqlx"
args = ["${@}", "--source", "adapter/migrations"]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }

[tasks.psql]
command = "docker"
args = [
  "run",
  "-it",
  "--rm",
  "--network",
  "host",
  "-v",
  "${PWD}:/work",
  "postgres:latest",
  "psql",
  "${DATABASE_URL}",
  "${@}",
]

[tasks.initial-setup]
command = "docker"
args = [
  "run",
  "-it",
  "--rm",
  "--network",
  "host",
  "-v",
  "${PWD}:/work",
  "postgres:15",
  "psql",
  "${DATABASE_URL}",
  "-f",
  "/work/data/initial_setup.sql",
]

[tasks.sort-cargo-toml]
command = "taplo"
args = ["fmt", "--option", "reorder_keys=true"]
install_crate = { crate_name = "taplo-cli", binary = "taplo-cli", test_arg = "--help" }

## Documentation tasks
[tasks.doc]
dependencies = ["pu2png"]

[tasks.pu2png]
command = "bash"
dependencies = ["generate-er"]
args = ["design/pu2png.sh"]

[tasks.generate-er]
command = "bash"
install_crate = { crate_name = "sqlant", binary = "sqlant", test_arg = "--help" }
args = ["design/generate-er.sh"]
