[config]
default_to_workspace = false

[tasks.set-env]
env_files = [".env"]

# ===== Build tasks =====
[tasks.compose-up-postgres]
extend = "set-env"
args = ["compose", "up", "-d", "postgres"]
command = "docker"

[tasks.migrate]
extend = "set-env"
dependencies = ["compose-up-postgres"]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }
script = '''
#!/bin/bash
export DATABASE_URL="postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"
echo "DATABASE_URL=$DATABASE_URL"
sqlx migrate run --source data_layer/adapter/migrations
'''

[tasks.sqlx-prepare]
extend = "set-env"
dependencies = ["migrate"]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }
script = '''
#!/bin/bash
cd data_layer/adapter
export DATABASE_URL="postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"
cargo sqlx prepare
'''

[tasks.before-build]
run_task = [{ name = ["sqlx-prepare"] }]

[tasks.compose-build]
extend = "set-env"
dependencies = ["before-build"]
script = '''
#!/bin/bash
docker compose build --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1
'''

[tasks.compose-build-no-cache]
extend = "set-env"
args = ["compose", "build", "--pull", "--no-cache", "--progress=plain"]
command = "docker"
dependencies = ["before-build"]

# ===== Test tasks =====
[tasks.nextest]
extend = "set-env"
dependencies = ["before-build"]
script = '''
#!/bin/bash
docker run --rm server cargo nextest run --workspace --status-level all --test-threads=1 "${@}"
'''

# ===== Utility tasks =====

[tasks.reformat]
script = '''
#!/bin/bash
cargo fmt -- --emit files
'''

[tasks.migrate-revert]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }
script = '''
#!/bin/bash
export DATABASE_URL="postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"
migration=$(find data_layer/adapter/migrations -type f -name "*down.sql" | sort -r)
for m in ${migration[@]}; do
  echo "Reverting migrations for $m"
  until sqlx migrate revert --source data_layer/adapter/migrations; do
    sleep 1
  done
done
'''

[tasks.sqlx]
args = ["${@}", "--source", "data_layer/adapter/migrations"]
command = "sqlx"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.7.3" }

[tasks.sort-cargo-toml]
args = ["fmt", "--option", "reorder_keys=true"]
command = "taplo"
install_crate = { crate_name = "taplo-cli", binary = "taplo-cli", test_arg = "--help" }

[tasks.backup-db]
extend = "set-env"
dependencies = ["compose-up-postgres"]
script = '''
#!/bin/bash
docker compose exec postgres pg_dump -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} > target/backup.postgres.dump
'''

# ====== Documentation tasks ======
[tasks.doc]
dependencies = ["pu2png"]

[tasks.pu2png]
args = ["design/pu2png.sh"]
command = "bash"
dependencies = ["generate-er"]

[tasks.generate-er]
args = ["design/generate-er.sh"]
command = "bash"
install_crate = { crate_name = "sqlant", binary = "sqlant", test_arg = "--help" }

# ====== Command tasks ======
[tasks.help]
extend = "set-env"
dependencies = ["before-build"]
args = [
  "compose",
  "run",
  "--rm",
  "--entrypoint",
  "",
  "server",
  "/app/target/release/server",
  "help",
  "${@}",
]
command = "docker"

[tasks.start-dashboard]
extend = "set-env"
dependencies = ["before-build"]
script = "docker compose up -d"

[tasks.collect-articles]
extend = "set-env"
args = [
  "compose",
  "run",
  "--rm",
  "--entrypoint",
  "",
  "server",
  "/app/target/release/server",
  "collect-articles",
  "${@}",
]
command = "docker"
dependencies = ["before-build"]

[tasks.add-academic-paper]
extend = "set-env"
args = [
  "compose",
  "run",
  "--rm",
  "--entrypoint",
  "",
  "server",
  "/app/target/release/server",
  "add-academic-paper",
  "${@}",
]
command = "docker"
dependencies = ["before-build"]

[tasks.notify-web-articles-to-slack]
extend = "set-env"
command = "docker"
dependencies = ["before-build"]
args = [
  "compose",
  "run",
  "--rm",
  "--entrypoint",
  "",
  "server",
  "/app/target/release/server",
  "notify-web-articles-to-slack",
]
