[package]
edition.workspace = true
license.workspace = true
name = "shared"
publish.workspace = true
version = "0.1.0"

[dependencies]
thiserror.workspace = true
sqlx.workspace = true
anyhow.workspace = true
serde.workspace = true
uuid.workspace = true
